name: CI Check Monorepo

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'api/soro-api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'
      - 'api/soro-api/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Frontend steps
      - name: Frontend | Linting
        run: pnpm --filter client lint

      - name: Frontend | Type Checking
        run: pnpm --filter client type-check

      - name: Frontend | Tests
        run: pnpm --filter client test

      - name: Frontend | Check for vulnerabilities
        run: pnpm --filter client audit --prod --audit-level=high

      - name: Frontend | Build
        run: pnpm --filter client build

      # Backend steps
      - name: Backend | Linting
        run: pnpm --filter soro-api lint

      - name: Backend | Type Checking
        run: pnpm --filter soro-api type-check

      - name: Backend | Tests
        run: pnpm --filter soro-api test

      - name: Backend | Check for vulnerabilities
        run: pnpm --filter soro-api audit --prod --audit-level=high

      - name: Backend | Build
        run: pnpm --filter soro-api build
